CREATE VIEW ADMINS AS
    SELECT USER.UserID, Name, Email
    FROM USER, ADMINSTRATOR
    WHERE USER.UserID = ADMINSTRATOR.UserID;

CREATE VIEW SPONSORS AS
    SELECT USER.UserID, Name, Email
    FROM USER, SPONSOR
    WHERE USER.UserID = SPONSOR.UserID;

CREATE VIEW DRIVERS AS
    SELECT USER.UserID, Name, Email
    FROM USER, DRIVER
    WHERE USER.UserID = DRIVER.UserID;
